plugins {
    id 'base'
}

allprojects {
    group = 'lab5'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    buildDir = "${rootProject.projectDir}/.gradle-build/${project.name}"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}

tasks.register('runServer') {
    group = 'application'
    description = 'Runs the server module'
    dependsOn ':server:runServer'
}

tasks.register('runClient') {
    group = 'application'
    description = 'Runs the client module'
    dependsOn ':client:runClient'
}
